// DO NOT EDIT
  // this file is generated by /internals/populate-icons script
  import React from 'react'
  // @ts-ignore
  import Icon from 'react-feather/dist/icons/arrow-up-right'
  import IconBase from '../../icon-base'

  function IconArrowUpRight(props: any) {
    return <IconBase icon={Icon} {...props} />
  }

  export default IconArrowUpRight
  