// DO NOT EDIT
  // this file is generated by /internals/populate-icons script
  import React from 'react'
  // @ts-ignore
  import Icon from 'react-feather/dist/icons/bar-chart-2'
  import IconBase from '../../icon-base'

  function IconBarChart2(props: any) {
    return <IconBase icon={Icon} {...props} />
  }

  export default IconBarChart2
  